facebook/ds2

- Sources/Host/POSIX/ProcessSpawner.cpp
Using ptsname gets us a warning on Android builds because it is not
reentrant.
> Use ptsname_r instead of ptsname.

- .travis.yml
- CMakeLists.txt
ds2 needs to link with a thread library to run correctly
with llgs test.
> Fix a test failure on Linux-x86_64

- .travis.yml
Some warnings appear only when building release (rare), and some bugs
only occur with release builds (enabled by some optimizations). This
change makes everything build both release and debug so we can catch
these.
> Add release builds to travis.

- Sources/GDBRemote/PacketProcessor.cpp
LLGS test suite always sends packets with 0 checksum. We end up printing
a ton of useless warnings in this case.
> Lower checksum failure logs from Warning to Info.

- Support/Scripts/common.sh
- Support/Scripts/run-llgs-tests.sh
- Support/Testing/Hacks-to-use-ds2-instead-of-llgs.patch
The testing infra moves too much on upstream master. Stabilize on
release_36 so it makes everyone's life easier.
> Use release_36 branch for llgs tests.

- Headers/DebugServer2/Architecture/Registers.h
- Headers/DebugServer2/Host/Platform.h
- Headers/DebugServer2/Target/ThreadBase.h
- Headers/DebugServer2/Target/Windows/Process.h
- Headers/DebugServer2/Types.h
- Headers/DebugServer2/Utils/Log.h
- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/GDBRemote/Structures.cpp
- Sources/Host/Windows/Platform.cpp
- Sources/Target/Linux/Process.cpp
- Sources/Target/Linux/Thread.cpp
- Sources/Target/POSIX/Thread.cpp
- Sources/Target/Windows/Process.cpp
- Sources/Target/Windows/Thread.cpp
- Sources/Target/Windows/X86/ProcessX86.cpp
This will allow us to properly decode Windows StopInfo.
> Move decoding of stop reasons to OS-specific code.

- Sources/Target/Linux/Thread.cpp
This change ensures ds2 handles thread exit cleanly.
Previously DS2 updates a thread and then checks for `_stopInfo.event`. This leads to a problem where a thread placeholder remains for too long and when `updateState()` invokes `ReadStat`, there is no such thread to be found in `/proc/...`. This change simply checks `_stopInfo.event` first and return early if the thread has already exited.
> Handle Thread Exit Cleanly

- Headers/DebugServer2/GDBRemote/DummySessionDelegateImpl.h
- Headers/DebugServer2/GDBRemote/Session.h
- Headers/DebugServer2/GDBRemote/SessionDelegate.h
- Headers/DebugServer2/Target/POSIX/ELFProcess.h
- Headers/DebugServer2/Target/ProcessBase.h
- Headers/DebugServer2/Target/Windows/Process.h
- Headers/DebugServer2/Types.h
- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/GDBRemote/DummySessionDelegateImpl.cpp
- Sources/GDBRemote/Session.cpp
- Sources/Target/POSIX/ELFProcess.cpp
- Sources/Target/Windows/Process.cpp
I thought qModuleInfo was going to be required for Windows support, but we can probably do away without it. Still adding the current work I have so we have the stubs if we wanna implement it later on.
> Add stubs for qModuleInfo.

- Headers/DebugServer2/Architecture/ARM/CPUState.h
- Headers/DebugServer2/Base.h
- Headers/DebugServer2/Constants.h
- Sources/Architecture/ARM/RegistersDescriptors.cpp
- Sources/Architecture/ARM64/RegistersDescriptors.cpp
- Sources/Architecture/X86/RegistersDescriptors.cpp
- Sources/Architecture/X86_64/RegistersDescriptors.cpp
- Sources/GDBRemote/Structures.cpp
- Sources/Host/POSIX/Platform.cpp
- Sources/Host/Windows/Platform.cpp
- Tools/main.cpp
It turns out that __BYTE_ORDER__ and friends are not defined
by MSVC.  This lead to a bug, because expressions like
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
would evaluate as true, regardless of actual endianness.
With this change we stop using the aforementioned endianness
defines on Windows, and instead simply assume little endian.
This seems to be a safe assumption for modern Windows platforms.
> Add ENDIAN defines in Base.h. Fixes issue 49.

- Headers/DebugServer2/Utils/Log.h
- Main/main.cpp
- README.md
- Sources/GDBRemote/ProtocolInterpreter.cpp
- Sources/GDBRemote/SessionBase.cpp
- Sources/Utils/Log.cpp
You can now run ds2 with -R to see remote protocol packet dumps,
and -V to see just debug logs.
> Separate remote protocol logs from debug logs

- Headers/DebugServer2/GDBRemote/DebugSessionImpl.h
- Sources/GDBRemote/DebugSessionImpl.cpp
This packet provides lldb with information about a memory region.
> Implement qMemoryRegionInfo packet handling

- CMakeLists.txt
- Tools/JSObjects/CMakeLists.txt
- Tools/RegsGen2/CMakeLists.txt
Properly set compile flags, definitions, and properties on a per-target
basis, and make sure we propagate the necessary flags to subprojects.
> Cleanup our cmake files.

- CMakeLists.txt
- Headers/DebugServer2/Host/Linux/ExtraWrappers.h
- Headers/DebugServer2/Host/POSIX/AsyncProcessWaiter.h
- Sources/Host/FreeBSD/PTrace.cpp
- Sources/Host/Linux/PTrace.cpp
- Sources/Host/POSIX/AsyncProcessWaiter.cpp
- Sources/Target/Linux/Process.cpp
We can use waitpid instead, which seems to be easier to find on some
sysroots, and provides the functionality of wait4 minus rusage (which we
never used).
> Get rid of uses of wait4.

- Sources/GDBRemote/DummySessionDelegateImpl.cpp
DS2 doesn't support this packet, but was sending responses
indicating that it does.
> Stop sending success responses for qSymbol

- Sources/Utils/Log.cpp
This avoids a warning about androidLevel being potentially
uninitialized.
> Use DS2_UNREACHABLE in log level conversion.

- CMakeLists.txt
- Sources/Utils/Log.cpp
- Support/CMake/Toolchain-Android-ARM.cmake
- Support/CMake/Toolchain-Android-ARM64.cmake
- Support/CMake/Toolchain-Android-X86.cmake
- Support/CMake/Toolchain-Android-X86_64.cmake
- Support/CMake/Toolchain-Tizen-ARM.cmake
- Support/CMake/Toolchain-Tizen-X86.cmake
The dlopen stuff is usless as the binaries generated with the android
toolchain won't run on other systems anyway.
> Directly link against liblog on android.

- Sources/Utils/Log.cpp
Even if the log level doesn't allow, dump debug info to logcat.
> Always dump messages to logcat.

- Headers/DebugServer2/GDBRemote/Types.h
- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/GDBRemote/Structures.cpp
- Sources/Target/Windows/Process.cpp
We need ds2 to detach from the process before the process can finish terminating. This causes some complications in how we encode stop info, so that has been updated as well.
> Fix process termination with kill packet on Windows

- Headers/DebugServer2/Target/Windows/Process.h
- Sources/Target/Windows/Process.cpp
Allows ds2 to kill processes that are not already stopped.
> Enable interrupt packet handling on windows

- CMakeLists.txt
- Headers/DebugServer2/Host/Linux/ExtraWrappers.h
- Headers/DebugServer2/Utils/CompilerSupport.h
- Sources/Host/Linux/ExtraWrappers.cpp
This help prevents issues with ds2 being built with a certain sysroot
(that has some functions) and then run on a device with an older OS
versions that doesn't have these symbols.
> Always build all the linux syscall wrappers as weak.

- README.md
sas-ubuntu-vm.local is the actual name of a machine, so better have it as localhost :)
this might help the people who just copy paste...
to: @sas
> make README easier to understand for localhost

- Support/Scripts/run-lldb-tests.sh
On CentOS we build lldb before testing, and we re-run cmake every time.
We don't need to do that as the Makefile generated by cmake will re-run
it for us if it's needed.
> Do not re-run cmake every time in run-lldb-tests.sh.

- Support/Testing/Patches/Disable-broken-Concurrent-tests.patch
These are still flaky.
This reverts commit 05b29a476aed923353a1d60fb487442e2080fbe0.
> Revert "Re-enable Concurrent tests which no longer hang"

- Sources/Target/FreeBSD/X86/ProcessX86.cpp
- Sources/Target/FreeBSD/X86_64/ProcessX86_64.cpp
- Sources/Target/Linux/ARM/ProcessARM.cpp
- Sources/Target/Linux/X86/ProcessX86.cpp
- Sources/Target/Linux/X86_64/ProcessX86_64.cpp
ptrace calls will fail if the main thread is sleeping at the time of the call
> Use tid instead of pid for ptrace calls.

- Headers/DebugServer2/GDBRemote/Types.h
- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/GDBRemote/Structures.cpp
- Sources/Host/Linux/ARM/PTraceARM.cpp
When parsing the registers in XML LLDB expects:
- the register number for each register
- value_regnums and invalidate-regs to be in decimal, not hex
> Fix support for ARM VFP registers

- Sources/main.cpp
Store command at the beginning because we modify argv while parsing. Log towards the end of main, so that we're sure the desired log level has been set before logging.
> Record full ds2 launch command to the Debug log

- Headers/DebugServer2/Host/Darwin/PTrace.h
- Headers/DebugServer2/Host/FreeBSD/PTrace.h
- Headers/DebugServer2/Host/Linux/PTrace.h
- Headers/DebugServer2/Host/POSIX/PTrace.h
- Sources/Host/Darwin/PTrace.cpp
- Sources/Host/FreeBSD/PTrace.cpp
- Sources/Host/Linux/PTrace.cpp
- Sources/Host/POSIX/PTrace.cpp
- Sources/Support/POSIX/Stringify.cpp
A lot of code is identical between the Linux, FreeBSD and Darwin
implementations of our ptrace abstraction. This commit moves a couple of
functions up into the POSIX implementation.
There are probably more methods that could be moved in the same way.
> Remove some duplicate code in PTrace.

- Headers/DebugServer2/Host/Windows/ExtraWrappers.h
This allows us to call functions from kernel32.dll with the right
conventions, eg stdcall vs cdecl.
> Preserve calling conventions in CallK32Proc.

- CMakeLists.txt
- Headers/DebugServer2/Utils/Backtrace.h
- Sources/Support/POSIX/FaultHandler.cpp
- Sources/Utils/Backtrace.cpp
- Sources/Utils/Log.cpp
Output looks like this:
```
[2754761][PrintBacktrace] ERROR  : 0x000000004c717b ds2::Utils::PrintBacktrace()+0x17 (./ds2)
[2754761][PrintBacktrace] ERROR  : 0x000000004c7705 ds2::vLog(int, char const*, char const*, char const*, __va_list_tag*)+0x3d3 (./ds2)
[2754761][PrintBacktrace] ERROR  : 0x000000004c7886 ds2::Log(int, char const*, char const*, char const*, ...)+0xb1 (./ds2)
[2754761][PrintBacktrace] ERROR  : 0x000000004ce447 main+0x1925 (./ds2)
[2754761][PrintBacktrace] ERROR  : 0x007ff97b803b15 __libc_start_main+0xf5 (/lib64/libc.so.6)
[2754761][PrintBacktrace] ERROR  : 0x0000000049bc99 <NOT FOUND>+0x49bc99 (./ds2)
Aborted
```
> Stack traces

- Headers/DebugServer2/Target/Darwin/Process.h
- Headers/DebugServer2/Target/FreeBSD/Process.h
- Headers/DebugServer2/Target/Linux/Process.h
- Headers/DebugServer2/Target/POSIX/Process.h
- Headers/DebugServer2/Target/ProcessBase.h
- Headers/DebugServer2/Target/Windows/Process.h
- Sources/Target/Darwin/Process.cpp
- Sources/Target/FreeBSD/Process.cpp
- Sources/Target/Linux/Process.cpp
- Sources/Target/POSIX/Process.cpp
- Sources/Target/Windows/Process.cpp
This also puts a definition of `wait` in `ProcessBase` and adds
`override` on all implementations in lower classes.
> Remove the status argument to `Process::wait`

- .travis.yml
This causes issues with builds that start after we do two pushes in a
row. Travis `git clone`s and then does a checkout of the git hash that
needs to be tested. If we do a clone with a depth of 1, only the HEAD
hash will be available.
> Remove depth: 1 from travis config.

- Support/Scripts/run-lldb-tests.sh
This basically just runs the test. It doesn't try to build lldb, or
patch the tests, or anything. It's meant to be used by developers, after
the first run of run-lldb-tests.
> Add a `--fast` option to run-lldb-tests.sh.

- Headers/DebugServer2/Types.h
- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/GDBRemote/Structures.cpp
- Sources/Target/Windows/Thread.cpp
This commit contains a seemingly useless switch on the stop reason but
this will be used in later commits to implement automatic continue of
other types of stops, for instance thread creation, etc.
> Forward data from OutputDebugString to the debugger.

- Sources/GDBRemote/DebugSessionImpl.cpp
We were resuming only one thread, which led to some fancy deadlocks.
> Resume the whole process when required.

- Sources/main.cpp
This allows us to pass FdLeak tests with a log file.
> Fix argument order to fcntl.

- Headers/DebugServer2/Host/Windows/ExtraWrappers.h
WINBASEAPI expands to `__declspec(dllimport)`. We need these if we want
to avoid having an additional import thunk generated for each external
function call.
> Add missing WINBASEAPI to Windows declarations.

- Headers/DebugServer2/Architecture/X86/RegisterCopy.h
- Sources/Target/Windows/X86/ThreadX86.cpp
Incorrect `memset` after the last magical macro patch.
> Fix writeCPUState on Windows.

- Headers/DebugServer2/Architecture/ARM/CPUState.h
- Headers/DebugServer2/Architecture/ARM64/CPUState.h
- Headers/DebugServer2/Base.h
This actually renames array_size to array_sizeof also.
> Make array_sizeof work with CPUState structures.

- Support/Testing/Patches/Fix-platform-detection.patch
This patch come from the MacOSX branch. It's used to run the lldbtest on macosx.
> Detect darwin as platform during lldb tests

- Sources/Architecture/ARM/SoftwareBreakpointManager.cpp
Windows ARM (more precisely, WinPhone ARM) is a pure thumb environment,
so if the debugger is requesting a breakpoint of size 4, it's probably
an older/buggy version and we should enforce size 2.
> Force BP size to 2 on Windows ARM.

- Sources/Target/Linux/ARM/ProcessARM.cpp
Fixes thumb/arm mismatch if different threads are in different modes.
> Make sure to read CPUState on the correct thread on memory alloc/dealloc

- Headers/DebugServer2/Architecture/ARM/CPUState.h
ip and sp were swapped. This worked fine on Linux because we didn't use
the named registers directly.
> Fix incorrect ARM CPUState register definition.

- Headers/DebugServer2/GDBRemote/SessionBase.h
- Sources/GDBRemote/SessionBase.cpp
- Sources/main.cpp
The destructor for SessionBase will always free its channel in
the destructor, prevent double-frees
> Don't use unnecessary unique ptr in platform mode

- Doxyfile
- Headers/DebugServer2/Host/Linux/ExtraWrappers.h
- Headers/DebugServer2/Host/Windows/ExtraWrappers.h
This skips all the extra wrappers we have for Windows and Linux. These
are just redefinitions of system headers so we don't need to include
them in our documentation.
> Skip some function declarations when running doxygen.

- Sources/main.cpp
This fixes a deadlock, where the platform-mode ds2
was waiting on the pipe closes, lldb was waiting on
platform-mode ds2, and slave-mode ds2 was waiting on lldb.
> Make sure to cleanup pipes before waiting on connection from lldb

- Sources/Target/Windows/ARM/ThreadARM.cpp
Windows on ARM does this weird thing of setting the lowest bit of `pc`
in the `CONTEXT` structure (output structure of `GetThreadContext()`)
even though that register doesn't actually have the lowest bit set in
the CPU; only the thumb bit in `CPSR` indicates we are running in thumb
mode.
`lr` on the other hand does have the lowest bit set if the caller was a
thumb function so we shouldn't remove it.
> Do not touch `lr` when removing the thumb bit from `pc` on winphone.

- .travis.yml
Without this, travis defaults to ruby for some reason, and does some
useless work at the beginning to support ruby testing.
> Mark language as generic in travis config.

- Headers/DebugServer2/Host/Windows/ExtraWrappers.h
We will need that and this is not available to Windows Store apps.
> Add a declaration for VirtualQueryEx

- Sources/Target/Windows/Process.cpp
Specially on winphone, if we don't detach in this case, the debugged process keeps alive in a very weird state
> Detach from debugged process when closing connection

- Sources/Target/Windows/Process.cpp
The current version of LLDB is using a different set of permissions when creating pages in the target, which has triggered a bug in this code. This patch fixes this issue by adding a write permission whenever we want to write to a page, without changing the other existing permissions
> Adding write permissions before writing to a page

- Support/Testing/Travis/install.py
This prevents having to struggle with `brew install` then `brew update`,
and a bunch of `|| true` hacks.
> Use `brew reinstall`

- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/main.cpp
These are displayed every time we debug something and they clutter the
terminal without serving any purpose.
> Reduce the number of `Info` logs

- Support/Scripts/run-lldb-tests.sh
Allow the version of lldb used by the test suite to be overridden
with a pre-existing lldb binary, to save time on CentOS, and
to allow for customized (ie debug mode) builds to be used if desired.
> Make lldb executable configurable in the test suite

- .travis.yml
The goal for mac is to build on each major release (7.0, 8.0, etc) + the
latest release (which was 7.3 before, and is 8.0 now). When Xcode 8.1
comes out, we'll add a new build for that.
> Build on Xcode 8 too on travis

- Headers/DebugServer2/Host/Windows/ExtraWrappers.h
- Sources/Target/Windows/Process.cpp
- Sources/Target/Windows/Thread.cpp
Use WaitForDebugEventEx instead of WaitForDebugEvent
to properly handle unicode strings sent by OutputDebugStringW.
Apply clang-format to the diff:
clang-format -i -style=llvm -lines=248:261 Sources/Target/Windows/Thread.cpp
> Replace WaitForDebugEvent with WaitForDebugEventEx

- CMakeLists.txt
- Headers/DebugServer2/Host/Linux/ExtraWrappers.h
- Headers/DebugServer2/Host/POSIX/PTrace.h
- Sources/Target/POSIX/ELFProcess.cpp
This is more accurate than looking at flags the compiler (or other
toolchain components) might define. In this specific instance, we had a
problem because we were trying to build a ds2 binary for Tizen, using
the Android toolchain, so half of these checks were not accurate.
> Use CMake checks to determine features

- Sources/Target/Linux/Process.cpp
Here's a situation that happened to me:
address <- 0xa000
last <- 0xa000 (location right after a section)
start <- 0xa000 (first location of a section)
and in the mapping:
0x9000-0xa000 whatever.so
0xa000-0xb000 other.so
In this case, even though other.so occupies the space, we assume the space that other.so (the one we're looking for) is a hole, not a defined region. In this case, info.start is the correct address but info.length ends up being 0, which has some unintended consequences.
> Fixed unmapped memory region detection on Linux

- Headers/DebugServer2/Types.h
- Headers/DebugServer2/Utils/String.h
- Sources/GDBRemote/Structures.cpp
- Sources/Target/Linux/Process.cpp
When LLDB calls GetMemoryRegionInfo on a process that goes through GDBRemoteCommunicationClient, it communicates with ds2 to grab the MemoryRegionInfo from the process. However, in LLDB 4.0, they added a `name` field in the response packet. That is, in addition to `start`, `size`, and `permissions`, `name` is something you can expect to see. I have updated ds2 to reflect this.
> Add name field in MemoryRegionInfo response

- Sources/Target/Windows/Process.cpp
Changing MemoryRegionInfo broke Windows builds. For now, we can put an empty string until we can figure out what to properly put here.
> Fix Windows AppVeyor build to work with update to MemoryRegionInfo

- Sources/Target/Linux/Process.cpp
ProcFS::ReadProcessInfo was not properly populating the ProcessInfo struct (was filling it in with ds2's info since `_info.pid` == 0 initially) and we used ELFProcess::updateInfo as a fallback to update it correctly. This should fix things so that ProcFS::ReadProcessInfo doesn't incorrectly populate the ProcessInfo struct and ELFProcess::updateInfo can instead return early.
> Fix ProcFS population of ProcessInfo on Linux

- Support/Scripts/prepare-android-toolchain.sh
Prevents the script from failing if a previous installation exists. Should reduce some Travis flakiness.
> Force re-installation of android toolchain if directory already exists

- Sources/Host/FreeBSD/PTrace.cpp
- Sources/Host/FreeBSD/X86_64/PTraceX86_64.cpp
- Sources/Host/Linux/ARM/PTraceARM.cpp
- Sources/Host/Linux/ARM64/PTraceARM64.cpp
- Sources/Host/Linux/PTrace.cpp
- Sources/Host/Linux/X86/PTraceX86.cpp
- Sources/Host/Linux/X86_64/PTraceX86_64.cpp
- Sources/Host/POSIX/PTrace.cpp
This code wasn't doing anything because the pid was implicitly getting
converted back to a ptid anyway.
> Get rid of a useless ptid to pid conversion

- .travis.yml
- Support/Testing/Travis/before-install.py
- Support/Testing/Travis/script.sh
For some reason, `platform.linux_distribution()` is failing on travis now, causing our build to fail. I've hardcoded 'trusty' for the time being as it's [becoming the default linux test environment](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming). There doesn't seem to a be a super convenient way to get the distribution name, so let's put it as an environment variable.
> Pull correct llvm packages from llvm's apt repositories

- Support/Testing/Travis/install.py
platform.linux_distribution() is unreliable on travis. We should rely on environment variables set by our .travis.yml, as unclean as that might sound. This should fix our build.
> Install ninja-build instead of ninja when on trusty without using `platform.linux_distribution()`

- Support/Scripts/install-android-emulator.sh
- Support/Scripts/prepare-android-toolchain.sh
- Support/Scripts/run-gdb-tests.sh
- Support/Testing/Travis/script.sh
Currently one of the targets fails pretty consistently with the error `NAND: could not write file /home/travis/.android/avd/test.avd/userdata-qemu.img, No space left on device`. In this PR, I aim to try and reduce the amount of space as much as possible. Currently all I've done is delete the sdk's zip/tarball. If this isn't enough, I can stack more diffs deleting more things.
> Remove temporary zips and tarballs during setup for more space

- Support/Testing/Travis/script.sh
- Support/Testing/Travis/travis-hacks.sh
This is shitty hack. I feel bad about doing this, but I think it should fix our things in the short term while we come up with a better solution for the long term. I'm thinking we can probably play around with Travis settings until we find a sweet spot, but that will take more time to read the documentation and engage the Travis community.
> Remove perl5 and otp installs on travis

- Sources/Target/Common/ProcessBase.cpp
I tested this locally. We now can set watchpoints on Windows Desktop targets (both x86 and x86_64), so it's ok to remove this ifdef guard. This should be the last step.
> Enable HardwareWatchpointManager for Windows

- Sources/Core/BreakpointManager.cpp
> Fix typo in BreakpointManager comment

- CMakeLists.txt
- Headers/DebugServer2/Target/Linux/Process.h
- Sources/Target/Linux/Process.cpp
Instead of sticking with ptrace for every POSIX system, we can use
process_vm_readv and process_vm_writev on Linux. This will allow us to
do our memory operation with one syscall instead of many 4-byte reads
with ptrace.
If these fail, we still have a fallback to use the ptrace mechanism.
> Implement fast memory read/write on Linux

- Headers/DebugServer2/Types.h
- Sources/GDBRemote/Structures.cpp
- Sources/Target/Windows/Thread.cpp
- Sources/Utils/Stringify.cpp
We used to ignore these and continue the process without delivering the
exception to the user. Instead, we need to mark them appropriately and
deliver them to the inferior upon continuation.
The GDB protocol requires UNIX semantics for all interruptions so I
picked SIGUSR1 to represent user exceptions.
> Handle user exceptions properly on Windows

- Headers/DebugServer2/Host/Linux/ARM64/Syscalls.h
This was preventing us from allocating memory in the remote process being debugged occasionally. Sometimes we would luck out, allocate memory, and segfault instead :D. This should prevent that the allocation bug! :D
> Fix register clobbering in Linux-aarch64 mmap code preparation

- .travis.yml
The emulators don't seem to work for now, and I think we can live
without this target until we figure things out.
> Disable Android-X86 tests

- Headers/DebugServer2/Core/BreakpointManager.h
- Headers/DebugServer2/Core/HardwareBreakpointManager.h
- Headers/DebugServer2/Core/SoftwareBreakpointManager.h
- Headers/DebugServer2/Target/Linux/Thread.h
- Sources/Core/HardwareBreakpointManager.cpp
- Sources/Core/SoftwareBreakpointManager.cpp
- Sources/Core/X86/HardwareBreakpointManager.cpp
- Sources/GDBRemote/Structures.cpp
- Sources/Target/Linux/Thread.cpp
- Sources/Target/Windows/Thread.cpp
Things this PR accomplishes:
1) Properly encoding StopInfo for watchpoints on windows
2) Switch from using global hardware breakpoints to thread-local hardware breakpoints
3) Setting the correct StopInfo on hitting a hardware breakpoint.
I'm confident (1) is correct because of the way ds2 responds on linux, so I think it should also respond the same way on windows.
I'm less sure about (2), because I'm not sure if we were using global hardware watchpoints for a specific reason. This is needed for windows support though, because windows doesn't allow the use of global hardware breakpoints as described [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680632(v=vs.85).aspx).
I know (3) works as-is, but there's some duplication of code. My concern is that the hardware …
> Add support for watchpoints on Windows Desktop x86 and x86_64

- Support/Scripts/install-android-emulator.sh
- Support/Testing/Travis/before-script.sh
I'm going to go ahead and submit this now. I'm curious if the newer method of installing an install emulator somehow takes up less space or can create a smaller emulator image for android-x86. Additionally, this should lay the groundwork for being able to test on android arm64.
I'm hoping this can somehow help us reduce disk usage so we can get android-x86 testing properly again and I won't have to merge #504.
> Rewrite scripts for testing on Android

- Support/Scripts/build-windows.bat
Teach the runner script to look for Visual Studio 2017's development
environment setup script and fall back to 2015 otherwise.
> Support Visual Studio 2017

- Sources/GDBRemote/DebugSessionImpl.cpp
Summary: LLDB appears to support this, so let's advertise that ds2 does as well.
Test Plan:
Tested on android arm & x86:
```
< 136> send packet: $QPassSignals:04;06;07;08;0b;0e;1b;20;21;22;23;24;25;26;27;28;29;2a;2b;2c;2d;2e;2f;30;31;32;33;34;35;36;37;38;39;3a;3b;3c;3d;3e;3f;40#bb
<   6> read packet: $OK#9a
```
> Enable QPassSettings in lldb compat mode

- Sources/main.cpp
The word "KILLED" makes it sound like we actually got killed by a signal
or a crash even when we're doing a clean exit. This makes it more
explicit that we are terminating the debug server under "normal"
circumstances.
> Slightly better log messages for session start/exit

- .travis.yml
I'm under the impression most people are going to be building things on Darwin with Clang, as its a part of the default toolchain on OSX. I don't expect gcc to fail to build ds2 on Darwin if Clang works. 
Additionally, the Mac queues on Travis are frequently backed up and are a bottleneck in CI signal. Minimizing the amount of work we need to do on OSX is better imo.
> Remove CI builds for gcc on Darwin

- Support/Scripts/common.sh
- Support/Scripts/install-android-emulator.sh
- Support/Scripts/run-lldb-tests.sh
- Support/Testing/Travis/before-script.sh
- Support/Testing/Travis/install.py
The adb used by travis is too old to work with the most up-to-date emulators in the android SDK. We should use the adb that ships with the SDK instead.
> Update scripts to fix Travis tests

- Support/Scripts/prepare-android-ndk.sh
if install.py flakes because apt-get fails, this script will fail since it tries to do something that it can't. This is why the build on master is failing.
> Remove previously installed android NDK in case install.py flakes

- README.md
When moving us to the LLDB 5.0 test suite, I added a new script to conform to how upstream tests. However, the README contains no instructions on how to test on an android device. I added a small section to shed some light on how that should work.
> Update docs for testing on Android

- README.md
Moving to CircleCI means we can add a fancy new badge to our README.md
> Add CircleCI build badge to README

- Sources/Host/Common/Platform.cpp
I'm pretty sure we shouldn't be checking for ENDIAN_LITTLE if we want to return kEndianBig.
> Fix a typo in Platform::GetEndian

- Support/Testing/CircleCI/Dockerfile
- Support/Testing/CircleCI/install-cmake.sh
Ubuntu's official repositories have CMake version 3.5.1, but we want version 3.7 or greater. This script and Dockerfile change should allow us to build docker images with the correct version of CMake moving forward.
After we get this in, I'll push new docker images.
> Install a newer version of CMake on docker images

- .circleci/config.yml
We never added these, so CircleCI wasn't running them. :(
> Actually add the Linux platform targets to the workflows

- .circleci/config.yml
Let's move these, should be easier than moving Linux-x86 clang targets. :P
> Move Linux-X86_64-Clang targets to CircleCI

- .circleci/config.yml
- .travis.yml
I created a new configure step. Although there's some repetition, I can't think of a better way to do this without introducing another layer of indirection (and I strongly prefer we don't introduce some wrapper script just to choose an API level properly).
> Move Android API level 16 builds to CircleCI

- Sources/Host/Linux/ProcFS.cpp
- Sources/Support/POSIX/ELFSupport.cpp
I did this for two reason:
1) It felt strange to me that we were updating the value of `type` and `subType` if we resolved the CPUType correctly, but we otherwise left these alone... except 2 of the 3 calls changed the values to some `kCPUTypeAny` and `kCPUSubTypeInvalid` anyway. We can move these into `MachineTypeToCPUType` and avoid these 2 branches entirely.
2) Following (1), we no longer use the bool result except at one call site. It felt "dirty" to me that we were using the result of the call in some places and outright ignoring it elsewhere, so I changed the return type to `void` and instead examined what value the `type` reference had. I'm wondering what y'all think about this one.
Thoughts?
> Simplify ELFSupport::MachineTypeToCPUType

- .circleci/config.yml
Now that we can ssh into test machines, it would be super useful to
have logs saved from test runs
> Enable logs on CircleCI lldb tests

- CMakeLists.txt
> Use -rdynamic for non-static ds2 builds

- Support/Testing/CircleCI/Dockerfile
In order to more closely match CircleCI locally, we should be running the docker image slightly differently. Through experimentation and reading some discussions online, it looks like CircleCI runs the docker images in a more privileged mode. The instructions should try to match that.
> Update instructions for running docker image locally

- Support/Testing/CircleCI/Dockerfile
There's no indication anywhere, besides how the tags look themselves, how to actually choose a new tag when updating docker images. Getting concrete instructions down somewhere is a good thing imo.
> Update docker instructions to talk about tags and how we use them 

- Headers/DebugServer2/Core/BreakpointManager.h
- Headers/DebugServer2/Core/HardwareBreakpointManager.h
- Headers/DebugServer2/Core/SoftwareBreakpointManager.h
- Sources/Architecture/ARM/SoftwareSingleStep.cpp
- Sources/Core/ARM/SoftwareBreakpointManager.cpp
- Sources/Core/BreakpointManager.cpp
- Sources/Core/HardwareBreakpointManager.cpp
- Sources/GDBRemote/DebugSessionImpl.cpp
It's definitely true you can use ask what type of breakpoint you have, and get back an answer concerning its lifetime (Temporary, Permanent, etc). However, we also have BreakpointType describing whether or not its a software breakpoint, hardware breakpoint, what kind of watchpoint, etc.
I think `Lifetime` is a much clearer name to describe what this is supposed to represent.
> Rename Type in BreakpointManager to Lifetime

- Sources/Core/ARM/HardwareBreakpointManager.cpp
- Sources/Core/ARM/SoftwareBreakpointManager.cpp
- Sources/Core/X86/HardwareBreakpointManager.cpp
- Sources/Core/X86/SoftwareBreakpointManager.cpp
We shouldn't assert (and consequently die) when validating user input. Rather, we should just return an error and add some debug logs that lets us know that's happening.
I went through and added some logs to other breakpoint validation code as well.
> Remove assertions and add debug logs to breakpoint validation code

- Headers/DebugServer2/Core/BreakpointManager.h
- Headers/DebugServer2/Core/HardwareBreakpointManager.h
- Headers/DebugServer2/Core/SoftwareBreakpointManager.h
- Sources/Core/ARM/HardwareBreakpointManager.cpp
- Sources/Core/ARM/SoftwareBreakpointManager.cpp
- Sources/Core/BreakpointManager.cpp
- Sources/Core/X86/HardwareBreakpointManager.cpp
- Sources/Core/X86/SoftwareBreakpointManager.cpp
According to the gdb-remote protocol, if the debugger does not choose an
architecture-specific size for a breakpoint, it is valid for it to send
0 as the breakpoint size. This value indicates that the debugserver
should choose a breakpoint size.
I had a workaround in #600 that I've now removed and replaced with this commit. If the all the related Linux-x86{_64,} tests pass there, this should be good to go in.
> Add support for choosing breakpoint sizes

- Support/Testing/Blacklists/ds2/llvm_60.blacklist
This test was disabled as a part of moving to 6.0. I'd like to re-enable it. The first step is removing it from the blacklist to see what breaks, which is what this PR will do initially.
> Re-enable TestFloatTypes

- CMakeLists.txt
- Headers/DebugServer2/Architecture/X86/CPUState.h
- Headers/DebugServer2/Architecture/X86_64/CPUState.h
- Headers/DebugServer2/Host/Linux/ExtraWrappers.h
- Sources/Host/FreeBSD/X86_64/PTraceX86_64.cpp
- Sources/Host/Linux/X86/PTraceX86.cpp
- Sources/Host/Linux/X86_64/PTraceX86_64.cpp
- Sources/Target/Windows/X86/ThreadX86.cpp
I understand this is a big change, and will probably require a lot of time to digest. I'm sure there are a few improvements to be made in implementation, but I think the fundamental idea is correct.
I refactored this in the process of fixing TestRegisters. I believe our previous implementation of dealing with floating point registers was incorrect. I have refactored the code to fix at least some of the problems, but not all. I think I have fixed the following:
- fiseg/fioff/foseg/fooff were incorrectly aliased on x86_64. Especially strange given fiseg/foseg were aliased to cs.
- No support for xstate_header, and therefore no way of enabling features (e.g. x87, sse, avx) through the features mask.
- Incorrect read/writes to stmm registers. Specifically, we did not account for 6 bytes of …
> Fix x86 and x86_64 floating point register support on Linux

- Support/Testing/Blacklists/ds2/llvm_60.blacklist
I want to re-blacklist TestFloatTypes for Linux platform mode. It flakes.
> Reblacklist TestFloatTypes

- Support/Scripts/run-lldb-tests.sh
I did some refactoring, because it's not enough to just not set LLDB_DEBUGSERVER_PATH. instead, the idea is to set it to lldb-server-6.0.
I didn't add support for using lldb-server and the `--log` flag at the same time (since lldb-server does logging differently than ds2) but I bet it wouldn't be too hard to implement if we cared to see what lldb-server does.
I've run both the test suite with both ds2 and lldb-server. Surprisingly lldb-server has more failures, but the test suite ran on both.
Additionally I shuffled some code around.
> Refactor support for using lldb-server in run-lldb-tests.sh

- Support/Testing/Blacklists/ds2/general.blacklist
I'm going to just see how CircleCI reacts. It passed on Linux-X86_64 locally.
> Re-enable TestEnumTypes

- Headers/DebugServer2/Host/Linux/ExtraWrappers.h
xsave_struct needs to be the same size on both Linux-x86 and Linux-x86_64, but x86 only had space for 8 ymm high registers instead of 16 like on x86_64. We just treat the last 8 ymmh registers as padding on x86.
In the same spirit, I unified the fxsave_struct definition. That is, the last 8 xmm registers are treated as padding on x86.
Also I wasn't sure why this wasn't caught on CircleCI. :/
> Fix xsave structs for x86

- Headers/DebugServer2/Target/Linux/Process.h
- Sources/Target/Linux/Process.cpp
This will make it easier to add Linux-only functionality to PTrace for
instance.
> Make Process::ptrace() return a more specific type

- Support/Scripts/run-lldb-tests.sh
`FAIL: TestExprs2.ExprCommands2TestCase.test_more_expr_commands_dwarf (expression_command/test/TestExprs2.py)`
consistently occurs on master. Add this to follow up with a centos.blacklists addition to hide this flake.
> Add support in run-lldb-tests.sh to exclude centos tests

- Support/Scripts/run-lldb-tests.sh
- Support/Testing/Blacklists/ds2/centos.blacklist
Flakes on master on devservers.
> Add TestExprs2.ExprCommands2TestCase.test_more_expr_commands_dwarf to centos.blacklists

- Support/Scripts/start-android-emulator.sh
The emulator complains about not being able to use audio resources properly. We can disable it just like we disable graphics too.
> Pass -no-audio to android emulator

- Support/Scripts/run-lldb-tests.sh
Android-ARM is failing to create a socket given localhost or * as the
address. Darwin is definitively failing on `::getaddrinfo` when fed *.
So, for now:
Change run-lldb-tests.sh to use 127.0.0.1 instead of localhost or *
as the argument for the address for the socket connection
> Change run-lldb-tests.sh to use 127.0.0.1 instead of localhost or *

- CMakeLists.txt
It seems standard in llvm projects (e.g. llvm, swift) to have this just set to 1.
> Add setting to always save compile_commands.json file

- Headers/DebugServer2/Core/BreakpointManager.h
- Headers/DebugServer2/Utils/Enums.h
- Sources/Architecture/ARM/SoftwareSingleStep.cpp
- Sources/Core/BreakpointManager.cpp
- Sources/GDBRemote/DebugSessionImpl.cpp
Previously an enum life `Lifetime` was declared as a trio of `unsigned int`s with some support from the compiler to suggest that you don't use them incorrectly. However, C++11 introduced `enum class`es various template techniques to make this more typesafe.
1. Convert `BreakpointManager::Lifetime` from a bare `enum` to an `enum class`.
2. Template instantiate the necessary bitwise operators for the bitwise mathematics done in `BreakpointManager` (Headers/DebugServer2/Core/BreakpointManager.h:115).
3. Convert the usage sites of `Lifetime` to the new format.
> Add typesafe bitwise enums and convert Lifetime to use it

- Headers/DebugServer2/Host/Linux/PTrace.h
- Sources/Host/Linux/PTrace.cpp
- Sources/Target/Linux/Process.cpp
- Sources/Target/Linux/Thread.cpp
- Support/Scripts/run-lldb-tests.sh
- Support/Testing/Blacklists/ds2/x86_64.blacklist
It is possible for the inferior to experience a (roughly) simultaneous
SIGTRAP from stepping while also receiving a SIGTRAP/SIGSTOP pair from a
clone(3) call. Depending on the receiving order of the signals, ds2
could handle the situation improperly and miss out on the existance of
the cloned thread.
Modify the processing logic to check if we are simultaneously
experiencing a thread being stepped while that thread also calls
clone and, if so, handle the cloned child at within the function instead
of depending on the normal waitpid loop.
> Modify Linux::Process::wait() to account for a race condition involving a simultaneous clone & step

- Support/Testing/CircleCI/Dockerfile
Add arm64 to the CircleCI Dockerfile to enable aarch64 testing
> Add arm64 to CircleCI Dockerfile

- Support/Scripts/run-lldb-tests.sh
- Support/Testing/Blacklists/ds2/android-arm64.blacklist
TestReturnValue.ReturnValueTestCase segfaults and causes a core dump,
thus:
Disable it to enable the test suite to continue.
> Add a blacklisted test for android-arm64

- CMakeLists.txt
3.7 doesn't handle the android-ndk properly and can't find various c headers e.g. math.h, stdio.h. I'm not sure if 3.7.1..<3.10 will suffice, but since we have the install script for 3.10 in the repo I just chose 3.10.
> Update minimum cmake to 3.10

- CMakeLists.txt
I don't think we actually need 3.10, and some build hosts we have
internally use cmake 3.9.
> Lower cmake required version to 3.9

- Headers/DebugServer2/Target/ProcessDecl.h
- Headers/DebugServer2/Utils/Enums.h
These macros included a semicolon at the end of their definition which clang7 now complains about the double `;;` when the macro was used in source. 
../Headers/DebugServer2/Target/ProcessDecl.h:28:33: error: extra ';' outside of a 
function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
__FORWARD_DECLARE(Linux, Thread);
^
> Remove double ;; from macros

- Headers/DebugServer2/Utils/Log.h
- Sources/Core/ARM/SoftwareBreakpointManager.cpp
- Sources/Core/SoftwareBreakpointManager.cpp
- Sources/Core/X86/SoftwareBreakpointManager.cpp
- Sources/GDBRemote/DebugSessionImpl.cpp
- Sources/GDBRemote/PlatformSessionImpl.cpp
- Sources/GDBRemote/ProtocolInterpreter.cpp
- Sources/GDBRemote/Session.cpp
- Sources/GDBRemote/SessionBase.cpp
- Sources/GDBRemote/SlaveSessionImpl.cpp
- Sources/Host/Darwin/Mach.cpp
- Sources/Host/Darwin/PTrace.cpp
- Sources/Host/FreeBSD/PTrace.cpp
- Sources/Host/Linux/PTrace.cpp
- Sources/Host/POSIX/ProcessSpawner.cpp
- Sources/Host/Windows/ProcessSpawner.cpp
- Sources/Target/Common/ProcessBase.cpp
- Sources/Target/Darwin/Process.cpp
- Sources/Target/Darwin/Thread.cpp
- Sources/Target/Darwin/X86_64/ThreadX86_64.cpp
- Sources/Target/FreeBSD/Process.cpp
- Sources/Target/FreeBSD/Thread.cpp
- Sources/Target/Linux/Process.cpp
- Sources/Target/Linux/Thread.cpp
- Sources/Target/POSIX/Process.cpp
- Sources/Target/Windows/ARM/ThreadARM.cpp
- Sources/Target/Windows/Process.cpp
- Sources/Target/Windows/Thread.cpp
- Sources/Target/Windows/X86/ThreadX86.cpp
- Sources/Target/Windows/X86_64/ThreadX86_64.cpp
DS2LOG uses __FUNCTION__ which does not accurately refer to the
parent function when you are working with a lambda as shown from this
error message:
ds2/Sources/Target/Common/ProcessBase.cpp:149:7: warning: inside a
lambda, '__FUNCTION__' expands to the name of the function call
operator; consider capturing the name of the enclosing function
explicitly [misc-lambda-function-name]
DS2LOG(Debug,
^
MSVC's __FUNCTION__ behaves properly while GCC & clang require
__PRETTY_FUNCTION__ to replicate this. Conditionally using the right
version allows us to remove __DS2_LOG_CLASS_NAME__ as well.
> Change DS2LOG to use the proper compiler builtin function string

- Support/Scripts/tidy.py
The command assumes that there exists a compile_commands.json in the
current directory. If there isn't then you must pass the
`--ccdb path-to-db` flag
> Add a script to run clang-tidy over the codebase

- CMakeLists.txt
ds2 is a routinely used binary on Windows that's not attached to our internal toolchain. Having an install target is useful.
> Add cmake install for ds2

- Headers/DebugServer2/Target/FreeBSD/Process.h
Added `override`.
```
Fixes:
[ 27%] Building CXX object CMakeFiles/ds2.dir/Sources/Target/Common/ThreadBase.cpp.o
/usr/bin/c++  -DTEST_FREEBSD_BUILD -I/root/src/ds2/Headers -I/root/src/ds2/Tools/JSObjects/Headers -Wall -Wextra -Werror -Wno-unused-parameter -Wcomma -Wdeprecated -Wextra-semi -Wfloat-equal -Winconsistent-missing-override -Wmissing-prototypes -Wnon-virtual-dtor -Wshadow -std=c++11 -o CMakeFiles/ds2.dir/Sources/Target/Common/ThreadBase.cpp.o -c /root/src/ds2/Sources/Target/Common/ThreadBase.cpp
In file included from /root/src/ds2/Sources/Target/Common/ThreadBase.cpp:12:
In file included from /root/src/ds2/Headers/DebugServer2/Target/Process.h:20:
/root/src/ds2/Headers/DebugServer2/Target/FreeBSD/Process.h:51:13: error: 'enumerateAuxiliaryVector' overrides a member function but …
```
> Fix build for FreeBSD

- CMakeLists.txt
The cmake logic checked if the compiler was MSVC and assumed that meant
you were using Visual Studio as a generator. However, using MSVC along
with Ninja is valid. Thus, fix up the ARCH_NAME to account for this work
flow.
> Fix Cmake for Ninja MSVC builds

- Support/Scripts/tidy.py
Use ==/!= to compare str, bytes, and int literals.
```
>>> slashes = "/"
>>> slashes += "/"
>>> slashes == "//"
True
>>> slashes is "//"
False
```
[flake8](http://flake8.pycqa.org) testing of https://github.com/facebook/ds2 on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./Support/Scripts/tidy.py:41:11: F632 use ==/!= to compare str, bytes, and int literals
while current_directory is not "/":
^
1     F632 use ==/!= to compare str, bytes, and int literals
1
```
> Identity is not the same things as equality in Python
