facebook/ds2

Headers/DebugServer2/Host/Windows/Platform.h, Sources/Host/Windows/Platform.cpp, Sources/Host/Windows/ProcessSpawner.cpp
We still keep everything as std::string in the rest of the code, but we
get wstrings and convert them back to UTF-8 std::strings.
=> Use unicode APIs for Windows.

.travis.yml
This PR contains fixes to parsing errors in .travis.yml, and marks the llgs test suite as "failok".
=> Fix .travis.yml.

Sources/Host/Linux/ProcFS.cpp
malloc without free. Replace with stack buffer.
=> Fix a few memory leaks in ProcFS.cpp.

Headers/DebugServer2/Types.h
These are not used, get rid of them.
=> Remove exception fields from TrapInfo.

Sources/GDBRemote/DebugSessionImpl.cpp, Sources/GDBRemote/Structures.cpp, Sources/Target/Windows/Thread.cpp
=> Fix Windows single-stepping.

.travis.yml, Support/CMake/Toolchain-Linux-X86_64-Clang.cmake, Support/Scripts/prepare-android-toolchain.sh, Support/Testing/Travis/before-install.py, Support/Testing/Travis/install.py, Support/Testing/Travis/script.sh
=> Add clang builds to travis.

CMakeLists.txt, Main/main.cpp, README.md, Sources/Utils/Log.cpp, Support/CMake/Toolchain-Android-ARM.cmake, Support/CMake/Toolchain-Android-ARM64.cmake, Support/CMake/Toolchain-Android-X86.cmake, Support/CMake/Toolchain-Android-X86_64.cmake
Main improvement here is to be able to log to android logcat.
=> Logging improvements.

Headers/DebugServer2/GDBRemote/Session.h, Headers/DebugServer2/GDBRemote/Types.h, Sources/GDBRemote/ProtocolInterpreter.cpp, Sources/GDBRemote/Session.cpp, Sources/GDBRemote/Structures.cpp, Tools/JSObjects/Headers/JSObjects/JSObjects.h, Tools/JSObjects/Sources/JSObjects.cpp
Allows for batch-wise communication of thread stop information to lldb
=> Implement jThreadsInfo packet

Sources/Target/Windows/Process.cpp, Sources/Target/Windows/Thread.cpp
=> Basic threading support for Windows.

README.md
=> Less pixelated build badge

README.md
Update filename to be displayed in an inline code block.
=> Fix Mkdown syntax

Headers/DebugServer2/Target/FreeBSD/Process.h, Headers/DebugServer2/Target/Linux/Process.h, Headers/DebugServer2/Target/Windows/Process.h, Sources/GDBRemote/Structures.cpp, Sources/Host/Windows/Platform.cpp, Sources/Target/FreeBSD/Process.cpp, Sources/Target/Windows/Process.cpp, Tools/JSObjects/Sources/JSObjects.cpp
This includes @fjricci's changes from PR#107.
=> Windows attach support.

Support/Testing/Patches/Disable-broken-ThreadExit-tests.patch, Support/Testing/Patches/Fix-Timeout.patch
Should prevent most test flakiness on dosep
=> Add verbose logging to dosep.py

CMakeLists.txt, Headers/DebugServer2/Utils/Log.h, Sources/Architecture/X86/SoftwareBreakpointManager.cpp, Sources/Host/Common/Socket.cpp, Sources/Host/POSIX/ProcessSpawner.cpp
=> Enable some builds with -Werror.

Sources/main.cpp
This works around issues with name resolution.
=> Use IP for localhost.

Headers/DebugServer2/Host/Linux/PTrace.h
This is verbose but really helpful for debugging.
=> Dump all ptrace commands to debug log.

.travis.yml
This should make things negligibly faster.
=> Reduce git clone depth on Travis.

.travis.yml, CMakeLists.txt, Headers/DebugServer2/Host/POSIX/PTrace.h, Headers/DebugServer2/Support/StringifyPrivate.h, Headers/DebugServer2/Types.h, Headers/DebugServer2/Utils/Paths.h, Sources/GDBRemote/DebugSessionImpl.cpp, Sources/Host/Linux/Platform.cpp, Sources/Target/POSIX/ELFProcess.cpp, Sources/Utils/Log.cpp, Sources/Utils/Paths.cpp
This mostly affects debugging on Tizen and android when attaching to a running app.
=> Fix handling of dynamic libraries on Linux targets.

Headers/DebugServer2/Utils/Paths.h
=> Fix a typo in a comment.

Sources/Host/POSIX/ProcessSpawner.cpp
Also some fancy braces are included in this change.
=> Return a slightly more precise error in POSIX::ProcessSpawner.

Headers/DebugServer2/Host/Linux/ExtraWrappers.h, Headers/DebugServer2/Host/POSIX/PTrace.h, Sources/Host/Linux/ARM/PTraceARM.cpp, Sources/Support/POSIX/Stringify.cpp, Sources/Target/POSIX/ELFProcess.cpp, Sources/Utils/Backtrace.cpp, Support/CMake/Toolchain-Tizen-ARM.cmake, Support/CMake/Toolchain-Tizen-X86.cmake, Support/Testing/Travis/before-install.py, Support/Testing/Travis/install.py
Just stop using the android toolchain for tizen builds.
=> Fix tizen builds

Headers/DebugServer2/Target/Darwin/MachOProcess.h, Headers/DebugServer2/Target/POSIX/ELFProcess.h, Headers/DebugServer2/Target/ProcessBase.h, Headers/DebugServer2/Target/Windows/Process.h, Sources/GDBRemote/DebugSessionImpl.cpp, Sources/Target/Darwin/MachOProcess.cpp, Sources/Target/POSIX/ELFProcess.cpp
Bad design :)
Also, this seemed fairly useless, and we should rework the ELFProcess
class to implement auxv enumration and library enumeration elsewhere.
=> Get rid of Process::isELFProcess.

Sources/Host/FreeBSD/ProcStat.cpp
=> Fix FreeBSD build.

Headers/DebugServer2/Target/ThreadBase.h, Headers/DebugServer2/Target/Windows/Process.h, Headers/DebugServer2/Utils/Log.h, Headers/DebugServer2/Utils/Stringify.h, Sources/GDBRemote/DebugSessionImpl.cpp, Sources/Target/Common/ProcessBase.cpp, Sources/Target/Common/ThreadBase.cpp, Sources/Target/POSIX/Process.cpp, Sources/Target/Windows/Process.cpp, Sources/Target/Windows/Thread.cpp, Sources/Target/Windows/X86/ThreadX86.cpp, Sources/Utils/Stringify.cpp, Support/Scripts/build-windows.bat
This is still WIP, but will include proper multi-thread single-stepping as well as full handling of OutputDebugString from inferiors.
=> Windows improvements.

Headers/DebugServer2/Host/Darwin/Platform.h, Sources/Host/Darwin/Platform.cpp
I just add the likeliest errors, but we will need to add more in the future.
=> Create TranslateKernError for Darwin kernel error

README.md, Sources/GDBRemote/PlatformSessionImpl.cpp, Sources/main.cpp, Support/Scripts/run-lldb-tests.sh
=> Make remote debug argument match gdbserver

Sources/Target/Windows/ARM/ThreadARM.cpp
This confuses the debugger, and is not what the CPU's PC register
actually contains. Get rid of it so everything works in sync properly.
=> Clear thumb bit from Windows register context.

Headers/DebugServer2/GDBRemote/Session.h, Headers/DebugServer2/Host/POSIX/ProcessSpawner.h, Headers/DebugServer2/Host/Windows/ProcessSpawner.h, Sources/GDBRemote/PlatformSessionImpl.cpp, Sources/GDBRemote/Session.cpp, Sources/Host/POSIX/ProcessSpawner.cpp, Sources/Host/Windows/ProcessSpawner.cpp
This was mostly implemented already as the now-non-existent qPlatform_RunCommand packet.
=> Implement qPlatform_shell

README.md
=> Build instructions for old Android.

Support/Scripts/common.sh, Support/Scripts/run-lldb-tests.sh, Support/Testing/Travis/install.py, Support/Testing/Travis/script.sh
This includes using ninja for builds on travis.
=> Some build changes

Support/Testing/Travis/install.py
Fixes install script on Ubuntu 16.04
=> Use default jdk version

Support/Testing/Travis/before-install.py
All that's needed for the scripts to work locally with xenial.
=> Add support for non-trusty llvm apt packages

Sources/Target/Windows/Process.cpp, Support/Scripts/run-lldb-tests.sh, Support/Testing/Patches/memory-region-info.patch
=> Fix Travis build failures introduced by memory region packet changes

Sources/Target/POSIX/ELFProcess.cpp
This is a step towards refactoring generalized ELF Process functionality. Getting the address containing shared library info is kind of a complicated thing, and I'm not sure there's any 100% foolproof way of doing it easily (I hope I eat my words). Specifically, here is how it works:
First: In an ELF file, we have a program header (PHDR) used by the dynamic linker to figure out how to actually build a process image from the file. The ELF specification says this is optional, but when you have an executable it is necessary. We can expect it to exist for things we want ds2 to attach to (I think). Next, we recognize that the ELF header is no bigger than 64 bytes (ELF32 is 52 bytes). This is convenient, as in practice, the PHDR is usually right after the header. It is possible that it will not …
=> Changing method of finding DT_DEBUG

Headers/DebugServer2/Core/HardwareBreakpointManager.h, Headers/DebugServer2/GDBRemote/Types.h, Headers/DebugServer2/Types.h, Headers/DebugServer2/Utils/Bits.h, Sources/Core/X86/HardwareBreakpointManager.cpp, Sources/GDBRemote/DebugSessionImpl.cpp, Sources/Target/Common/ProcessBase.cpp, Sources/Target/Linux/Thread.cpp
Gets around write-protected branch issues.
=> Intermediate commits for watchpoint PR

.travis.yml
Should fix issues with build errors
=> Disable secured env variables on travis

Support/Testing/Travis/install.py
Still running out of space, but not by much. This should buy us more space, possibly enough?
=> Run `apt-get clean` after installing packages

Sources/GDBRemote/Session.cpp, Sources/Utils/Log.cpp
This is used by lldb to test the speed of the link between the debugger
and the debug server.
=> Add support for qSpeedTest

.circleci/config.yml, .travis.yml, Support/Scripts/generate-register-descriptors.sh
Let's move this to CircleCI, seems easy enough.
=> Move Registers CI target to CircleCI

.circleci/config.yml, .travis.yml, Support/Scripts/generate-documentation.sh
=> Move the Documentation target from Travis to CircleCI

.travis.yml
=> Actually remove Linux-x86_64-Clang jobs from Travis

.circleci/config.yml, .travis.yml, Support/Scripts/run-lldb-tests.sh
=> Move Linux-X86-Clang targets to CircleCI

.circleci/config.yml, .travis.yml, Support/Scripts/run-gdb-tests.sh, Support/Testing/CircleCI/Dockerfile, Support/Testing/Patches/gdb/Disable-broken-break-tests.patch, Support/Testing/Patches/gdb/Disable-broken-step-bt-tests.patch
=> Move gdb tests to CircleCI

Headers/DebugServer2/Host/Socket.h, Sources/Host/Common/Socket.cpp
Convert Socket::State to a C++11 enum class
=> Change Socket::State to an enum class

Headers/DebugServer2/Host/Platform.h, Headers/DebugServer2/Utils/String.h, Sources/Host/Windows/Platform.cpp, Sources/Host/Windows/ProcessSpawner.cpp, Sources/Target/Windows/Process.cpp, Sources/Target/Windows/Thread.cpp
There was TODO and it looked like it was the right thing do.
Let's see if AppVeyor likes it. :)
=> Move NarrowToWideString and WideToNarrowString from Platform to Utils

Support/Scripts/generate-documentation.sh, Support/Scripts/generate-register-descriptors.sh, Support/Scripts/run-gdb-tests.sh, Support/Scripts/run-lldb-tests.sh, Support/Scripts/start-android-emulator.sh
Add flags to support scripts to allow flag-based arguments in addition to environment-based arguments.
=> Add flags to support scripts

Sources/Target/Linux/Process.cpp
Due to the non-deterministic nature of the signals being sent to the
cloned thread and the parent thread, `waitpid(... WNOHANG)` could end up
returning empty due to not having any child to wait for.
Remove `WNOHANG` so that we will wait for a child thread to be stopped
on clone given that we were just ignored by geteventmsg that there is a
thread to wait for.
=> Fix two bugs involving the timing of waitpid events

Support/Scripts/common.sh, Support/Scripts/run-lldb-tests.sh, Support/Testing/Patches/fix-test-suite-path.patch
Clean up some repetitive code, clean up some formatting and add an
option to run the test suite under control of PUDB.
=> Add some facilities to debug tests and clean up run-lldb-tests.py

Support/Scripts/run-lldb-tests.sh
Debugging the lldb test suite can require a version of liblldb.so
including debug symbols. Therefore, to make this easier to accomplish:
Add a --build-lldb flag to enable building lldb and running the test
suite with the newly built version.
=> Add flag to build lldb in the ds2 build tree

.circleci/config.yml, Support/Scripts/install-android-emulator.sh
This will need tested via the Dockerfile installation first. So just a placeholder for now.
=> Update install-android-emulator to latest sdk

Support/Scripts/test-protocol-latency.py
I'm planning on using this later on to automate testing of network
performance.
This is a script written by Gregory Clayton <gclayton@fb.com>.
=> Add a script to test network latency with ds2

.clang-tidy, Sources/GDBRemote/ProtocolInterpreter.cpp, Sources/GDBRemote/SessionBase.cpp, Sources/GDBRemote/SlaveSessionImpl.cpp, Sources/Target/Darwin/Process.cpp, Sources/Target/Darwin/Thread.cpp, Sources/Target/Darwin/X86_64/ProcessX86_64.cpp, Sources/Utils/POSIX/Stringify.cpp, Sources/main.cpp
clang-tidy detects a few minor issues. Fix them here.
=> Add .clang-tidy and fix a few issues it detects
